server:
  port: 8081
  ssl:
    key-store: certificate/appkey.p12
    key-store-type: PKCS12
    key-alias: spring-security-application
    key-store-password: password

security:
  secretKey: secret

logging:
  level:
    com.borykapp.secure1: WARN
    org.springframework.web: INFO
